feat: 레시피 추가, 업데이트 기능 구현
you-can-cook/Gobong pull request #14
Opened 2023-08-05 11:08 UTC by donghoony

## 개요 🧾

단순 레시피를 추가하고 수정하는 기능을 추가했습니다.

## 주의사항 ⚠

우선 현재로서는 사용자가 레시피 생성 시 조리도구 없음, 0분 소요인 상태로 레시피가 만들어집니다.

2023-08-05 14:16 UTC, redcarrot1 requested changes

2023-08-05 14:16 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/recipe/service/RecipeService.java
> +    public CreateRecipeResponse createRecipe(Long userId, String title, String introduction, List<String> ingredients,
인자 개수가 6개인 함수네요. 대신 DTO 객체를 넘기는게 어떤가요?(선택사항)

2023-08-05 14:16 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/request/CreateRecipeRequest.java
> +    private String title;
`string`에서는 `@NotBlank`로 검증하는게 어떤가요?

2023-08-05 14:16 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/request/CreateRecipeRequest.java
> +    private Difficulty difficulty;
`@ReqeustBody`로 json을 받을 때, enum타입을 직접 사용하면 다른 처리를 해주어야 합니다!
convert를 만드는 방법도 있고, enum 타입에 다른 처리를 하는 방법 등 다양한 방법이 있는 것 같습니다.

개인적으로는 String으로 받고 Custom Validator으로 검증하던지, 아니면 서비스단에서 검증하는게 좋을 것 같습니다.
exception을 커스텀으로 던질 수 있기 때문입니다.

2023-08-05 14:16 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/request/CreateRecipeRequest.java
> +    private List<@Valid UploadRecipeDetailRequest> recipeDetails;
`List` 자체에도 `@NotNull`을 붙이는게 어떤가요?
json에 `recipeDetails` 자체가 존재하지 않으면(빈 리스트와 다름) null이 넘어오게 되는데, 서비스 영역에서 List는 순회할 가능성이 높습니다. 이때 NullpointException을 던지는 것보다는 미리 검증하는게 더 좋을 것 같습니다.

근데 이거는 Client를 얼마나 신뢰할 것인가에 따라서 다를 것 같아요.

2023-08-05 14:17 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/request/CreateRecipeRequest.java
> +    private Difficulty difficulty;
https://www.inflearn.com/questions/728516/api-%EC%9E%91%EC%84%B1%EC%A4%91%EC%97%90-enum-type-%EB%AC%B8%EC%9D%98-%EB%93%9C%EB%A6%BD%EB%8B%88%EB%8B%A4

2023-08-06 08:57 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/recipe/service/RecipeService.java
> +    public CreateRecipeResponse createRecipe(Long userId, String title, String introduction, List<String> ingredients,
반영할게요~

2023-08-06 09:02 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/recipe/dto/request/CreateRecipeRequest.java
> +    private Difficulty difficulty;
`from` 메서드 추가하겠습니다

2023-08-06 11:07 UTC, redcarrot1 approved these changes

2023-08-06 11:29 UTC, merged