feat: 단계별 레시피 추가 및 업데이트 기능 구현
you-can-cook/Gobong pull request #15
Opened 2023-08-05 11:10 UTC by donghoony

## 개요 🧾

레시피에 단계별 레시피를 추가하는 기능을 구현했습니다.

## 주의사항 ⚠

업데이트 시 매번 모든 detail을 delete한 뒤에 새로 삽입하는데, 이게 최선인지는 모르겠네요. 좋은 아이디어가 생기면 리팩터링을 진행하겠습니다.
아무래도 단계별 레시피가 종속적으로 속해서 생기는 일 같기도 합니다..

매번 꼼꼼하게 확인해줘서 고마워요 👍🏼

2023-08-05 14:20 UTC, redcarrot1 reviewed
지금 앞선 PR 내용이 여기에도 `File changed`로 보여서 살짝 헷갈리네요.
중복 코멘트를 피하기 위해 앞에 있는 PR이 merge되면 리뷰 올릴께요!

2023-08-07 02:49 UTC, redcarrot1 requested changes

2023-08-07 02:49 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/recipedetail/service/RecipeDetailService.java
> +        recipeDetailRepository.deleteAll(recipe.getRecipeDetails());
`deleteAll()`에서는 리스트를 **for 문** 돌리면서 하나씩 삭제하게 됩니다.(대량의 쿼리)
따라서 `deleteAllInBatch`나 jpql을 사용하는 것을 추천드립니다.

만약 jpql을 사용한다면 아래와 같이 방식으로 작성할 수 있습니다.
```java
@Modifying
@Query("delete from Member as m where m.team = :team")
void deleteByTeam(@Param("team") Team team);
```

2023-08-07 04:07 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/recipedetail/service/RecipeDetailService.java
> +        recipeDetailRepository.deleteAll(recipe.getRecipeDetails());
`orphanRemoval`도 알아봤는데 이것도 건당으로 제거하네요.. 쿼리가 필요하긴 한가봐요

2023-08-07 06:23 UTC, donghoony commented
양방향 연결관계는 책임을 어디로 둬야할 지 애매해지네요.
양방향 연결관계를 끊고 테스트를 잘게 쪼갰습니다.
이제 `Detail`에서는 `recipe`와 관련된 일을 하지 않습니다. `detail`이 가지고 있는 `cookware`, `cookTime`을 합산하는 역할을 이곳에서 수행합니다.

2023-08-07 07:56 UTC, donghoony commented
> 양방향 연결관계는 책임을 어디로 둬야할 지 애매해지네요. 양방향 연결관계를 끊고 테스트를 잘게 쪼갰습니다. 이제 `Detail`에서는 `recipe`와 관련된 일을 하지 않습니다. `detail`이 가지고 있는 `cookware`, `cookTime`을 합산하는 역할을 이곳에서 수행합니다.

-> RecipeDetail에서 `recipe`의 총 조리도구 / 조리시간을 초기화할 수 있도록 했습니다.
Test 내에 두 개를 다 건드리는 경우 `@Transactional`을 추가했어요

2023-08-07 08:04 UTC, redcarrot1 approved these changes

2023-08-07 08:05 UTC, merged