feat: login service
you-can-cook/Gobong pull request #16
Opened 2023-08-05 13:44 UTC by redcarrot1

## 개요 🧾
RefreshToken Entity 생성, UserLoginService 생성

## 변경사항 🛠
로그인에 성공할 경우 RefreshToken을 DB에 저장합니다. 이때 id는 `userId`입니다.
RefreshToken이 기존 존재한다면 덮어쓰기합니다. 따라서 유효한 RefreshToken은 단 하나이며, 다른 기기에서 동시 로그인은 불가능합니다. 이를 통해 RefreshToken이 탈취되어도 유저의 재로그인을 통해 탈취된 토큰을 바로 무효화 시킬 수 있습니다.

`UserRepository`에서 쿼리 메소드가 정상적으로 작동하지 않아 JPQL을 직접 작성했습니다.
아마 `oAuth`에서 중간에 존재하는 대문자 때문에 발생하는 문제습니다.
ref: https://velog.io/@coastby/JPA-IllegalArgumentException-Unable-to-locate-Attribute-with-the-the-given-name-on-this-ManagedType

2023-08-05 14:26 UTC, donghoony requested changes

2023-08-05 14:26 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/user/entity/OAuthProvider.java
> +    }
Java8 Stream을 사용해 보는 건 어떤가요? Try-catch 없이 작성할 수 있습니다
```suggestion
    public static OAuthProvider from(String provider){
        return Arrays.stream(values())
                .filter(value -> value.toString().equalsIgnoreCase(provider))
                .findFirst()
                .orElseThrow(OAuthProviderNotFoundException::new);
    }
```
나아가서 `from`이라는 메서드 이름을 사용해도 괜찮을 것 같아요.

2023-08-05 14:26 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/user/repository/UserRepository.java
> +    Optional<User> findByOAuthProviderAndOAuthId(OAuthProvider oAuthProvider, String oAuthId);
버그라니 참 😮‍💨

2023-08-05 14:26 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/user/service/UserLoginService.java
> +        refreshTokenRepository.save(refreshToken);
> RefreshToken이 기존 존재한다면 덮어쓰기합니다. 따라서 유효한 RefreshToken은 단 하나이며, 다른 기기에서 동시 로그인은 불가능합니다. 

로그인은 Stateless하게 AccessToken으로만 검증하기 때문에 Refresh가 다르더라도 로그인 이후에 같은 AccessToken으로 유효한 동안에는 동시 로그인(인 것처럼) 접속이 가능한거죠?

2023-08-05 14:26 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/global/util/token/TokenManager.java
> +                .refreshTokenExpiredAt(refreshTokenExpiredAt)
토큰 자체에 만료일자가 담겨서 암호화됩니다.
클라이언트로 넘겨주게 되는 Json에 언제 토큰이 만료되는지 여부가 포함되어야 할 이유가 있나요?

2023-08-05 14:27 UTC, donghoony commented
확실히 서버에서 OAuth 관련 일을 하지 않으니 편리하긴 합니다만 고민할 게 많긴 또 많네요 😮

2023-08-05 14:38 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/user/service/UserLoginService.java
> +        refreshTokenRepository.save(refreshToken);
맞습니다. 현재 설정으로는 최대 2시간까지 access token을 이용하여 동시 로그인이 가능합니다.

2023-08-05 14:50 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/user/service/UserLoginService.java
> +        refreshTokenRepository.save(refreshToken);
다른 곳에서 동시 로그인은 어떻게 구현하나 궁금해지네요..

2023-08-06 11:18 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/global/util/token/TokenManager.java
> +                .refreshTokenExpiredAt(refreshTokenExpiredAt)
말씀하신 것처럼 클라이언트에서는 굳이 만료 시각을 따로 전달받을 필요가 없어서 response 클래스를 분리했습니다.

2023-08-06 11:19 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/user/entity/OAuthProvider.java
> +    }
반영했습니다.
그런데 `try-catch`를 사용하지 않고, `Array stream`으로 선형 탐색하는 특별한 이유가 있나요?

2023-08-06 11:27 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/user/entity/OAuthProvider.java
> +    }
저는 단순하게 Nest 단계를 하나 줄여서 코드의 가독성을 올릴 수 있다고 생각해요.
그 외에도 Stream을 활용함에 있어서 확장성 등도 생각할 수 있을 것 같네요

지금은 Provider의 개수가 많지 않아서 단순 선형탐색의 시간이 크진 않겠지만, 개수가 많아진다면 `Hashmap`을 고려할 수도 있습니다.

[reference](https://velog.io/@ljinsk3/Enum%EC%9D%98-%EC%9A%94%EC%86%8C%EB%A5%BC-%EC%A1%B0%ED%9A%8C%ED%95%98%EB%8A%94-%EB%B0%A9%EB%B2%95-%EB%B9%84%EA%B5%90-%ED%8C%A9%ED%86%A0%EB%A6%AC-%EB%A9%94%EC%84%9C%EB%93%9C-vs-HashMap)

2023-08-06 11:29 UTC, donghoony approved these changes
LGTM 👍🏼

2023-08-06 11:44 UTC, merged