feat: Argument Resolver 추가
you-can-cook/Gobong pull request #21
Opened 2023-08-08 07:11 UTC by redcarrot1

## 개요 🧾
Argument Resolver 생성

## 변경사항 🛠
request의 `AUTHORIZATION` 헤더에 담겨온 Access Token에서 추출한 `Long` 타입의 `userId`을 컨트롤러에서 파라미터로 받을 수 있습니다. 이때 `@UserId` 어노테이션을 붙여야 하고, 반드시 Long 타입으로 받아야 합니다.

```java
@GetMapping
public void test(@UserId Long userId) {
    System.out.println(userId);
}
```

2023-08-08 08:06 UTC, donghoony requested changes
이거 머지되면 컨트롤러 금방 되겠네요 👍🏼

2023-08-08 08:06 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/global/resolver/UserIdArgumentResolver.java
> +        token = token.split(" ")[1];
주어진 토큰에 띄어쓰기가 없을 경우 오류가 날 것 같습니다
split하지 말고 `startsWith`로 Bearer 확인, 'Bearer ' 이후에 Token이 들어오니까 특정 인덱스(6-7 이후) 뒤로 substring 후 trim해서 확인하는 게 나을 듯해요

2023-08-08 08:06 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/global/resolver/UserId.java
> +public @interface UserId {
로그인한 유저 아이디가 들어오니까 `AuthorizedUserId`는 어떤가요? 너무 넓은 범위 같아서 고민이 되네요.. `LoginUserId`정도만 돼도 좋을 것 같아요

2023-08-08 08:06 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/global/resolver/UserIdArgumentResolver.java
> +        boolean isLongClass = Long.class.isAssignableFrom(parameter.getParameterType());
`Long` 클래스 관련된 체크가 필요한가요?

2023-08-08 08:19 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/global/resolver/UserIdArgumentResolver.java
> +        token = token.split(" ")[1];
나아가서 해당 토큰을 뽑아내는 걸 함수 내지는 클래스로 뽑는 게 나을 것 같다는 생각을 했어요

2023-08-08 12:43 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/global/resolver/UserIdArgumentResolver.java
> +        token = token.split(" ")[1];
지금은 구현되어 있지 않지만 interceptor을 사용할 예정입니다.
interceptor와 resolver가 하는 일이 비슷하지만 (어쩌면 겹치지만), 임의로 하는 일을 분리하자면
1. interceptor: 헤더에 있는 토큰을 **검증**
2. resolver: 헤더에 있는 **토큰을 해석해 파라미터로 넘기기**

이렇게 역할을 분리하는거에 대해 어떻게 생각하시나요?

2023-08-08 12:50 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/global/resolver/UserIdArgumentResolver.java
> +        boolean isLongClass = Long.class.isAssignableFrom(parameter.getParameterType());
resolver에서 Long 타입을 리턴하는데, (예를 들어) 컨트롤러에서 String 타입으로 파라미터를 받으면 `null`이 담겨집니다.

```java
@GetMapping
public String test(@UserId String userId) {
    System.out.println(userId); // null 출력
    return "test";
}
```

2023-08-08 12:53 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/global/resolver/UserId.java
> +public @interface UserId {
`LoginUserId` 로 변경했습니다.

2023-08-08 14:17 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/global/resolver/UserIdArgumentResolver.java
> +        boolean isLongClass = Long.class.isAssignableFrom(parameter.getParameterType());
지금 다시 확인해보니깐 아에 에러가 뜨네요
`java.lang.IllegalStateException: argument type mismatch`

2023-08-08 14:22 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/global/resolver/UserIdArgumentResolver.java
> +        boolean isLongClass = Long.class.isAssignableFrom(parameter.getParameterType());
저게 없어도 해당 어노테이션이 붙으면 넘겨주는 게 있는데 필요성이 궁금했네요, 어차피 저희가 넣어주는거라 Long을 잊진 않을 것 같기도 하고..? 안전장치겠죠

2023-08-08 14:23 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/global/resolver/UserIdArgumentResolver.java
> +        token = token.split(" ")[1];
Interceptor, Resolver, Token 뽑아내는 것 세개 다 다른 역할이라고 생각해요

2023-08-08 14:27 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/global/resolver/UserIdArgumentResolver.java
> +        boolean isLongClass = Long.class.isAssignableFrom(parameter.getParameterType());
`supportsParameter`에서 `false`를 리턴하면 null을 넘기고, `true`를 리턴하면 해당 값을 바로 넘기는데 받는 쪽에서 `Long`이 아니라서 그렇게 되네요

2023-08-09 00:22 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/global/resolver/UserIdArgumentResolver.java
> +        token = token.split(" ")[1];
Interceptor에서 토큰 검증(헤더에 토큰 유무, Bearer 확인, 유효성 등)을 수행하고, Argument Resolver에서는 파라미터로 데이터를 넘기는 역할이라고 생각해요.
물론 Argument Resolver에서도 토큰 검증을 한번 더 할 수도 있겠지만, 저희 애플리케이션에서는 Argument Resolver를 사용하는 컨트롤러의 URL은 반드시 Interceptor를 통과하게 됩니다. 그러면 중복 로직이 발생하게 됩니다.

어느 수준까지 Argument Resolver에서 검증을 수행해야 할까요?

2023-08-09 04:07 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/global/resolver/UserIdArgumentResolver.java
> +        token = token.split(" ")[1];
resolver에서 토큰 String에서 검증하는것이 낫겠네요, 위에서 얘기한 split 문제는 해결해야겠습니다 👍🏼

2023-08-09 07:22 UTC, donghoony approved these changes
나머지는 다 괜찮아 보이네요 👍🏼

2023-08-09 07:22 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/global/resolver/LoginUserIdArgumentResolver.java
> +    private final String grantTokenType = "Bearer";
상수 변수명은 대문자로 가시죠~!
```suggestion
    private final String GRANT_TOKEN_TYPE = "Bearer";
```

2023-08-09 08:15 UTC, merged