feat: 평점 서비스 구현 및 테스트 작성
you-can-cook/Gobong pull request #5
Opened 2023-08-02 10:15 UTC by donghoony

## 개요 🧾

평점 서비스를 구현했습니다. 평점은 1점부터 5점까지 1점 단위로 줄 수 있습니다.
각각의 레시피에 대해서 한 번에 점수를 계산하기 위해, 레시피와 평점 사이를 양방향 연관관계를 두었습니다.
그에 따른 단위 테스트를 추가하고, 서비스에 대한 테스트도 작성했습니다.

## 변경사항 🛠

## 주의사항 ⚠

백엔드 브랜치에서 머지해오다가 컨플릭이 나서 다소 지저분할 수 있습니다,, 조심할게요 😢 
테스트 확인하고, 코드 잘 짜였나 확인해주시면 감사하겠습니다~

2023-08-02 13:27 UTC, redcarrot1 requested changes
고생하셨습니다~
개발은 답이 없는 문제가 많다 보니, 고민할 거리도 많은 것 같습니다.

2023-08-02 13:27 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/rating/dto/request/RateRecipeRequest.java
> +    private Long userId;
`userId`는 Argument Resolver를 통해 컨트롤러에서 받기 때문에 필드가 필요 없습니다.

2023-08-02 13:27 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/rating/entity/Rating.java
> +    public void validateRatingRange(Integer rating){
저는 DDD를 해본적이 없습니다. entity는 자료구조로 사용하고, 비즈니스 로직은 service 영역에서 처리해왔습니다.
동훈 형은 DDD의 시작인가요..(천재 신입 개발자다)
[읽을거리](https://www.inflearn.com/questions/117315/%EB%B9%84%EC%A7%80%EB%8B%88%EC%8A%A4-%EB%A1%9C%EC%A7%81%EA%B5%AC%ED%98%84-entity-vs-service)

2023-08-02 13:27 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/rating/service/RatingService.java
> +        recipeRepository.findById(recipeId).orElseThrow(RecipeNotFoundException::new);
데이터의 존재 여부만 확인하고 싶다면 `findBy`보다는 `exists~`를 사용하시는게 성능상 유리합니다.

2023-08-02 13:27 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/rating/service/RatingService.java
> +        Rating rating = ratingRepository.findByUserIdAndRecipeId(userId, recipeId)
여기서 `userId`와 `recipeId`를 쿼리 조건에 넣어서 `Rating`을 찾습니다.

37, 38번줄에서 `user`와 `recipe`가 DB에서 유효한지 찾는 과정이 필요할까요?

2023-08-02 13:27 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/recipe/entity/Recipe.java
> +    public double getAverageRating(){
N+1 문제가 발생할 수도 있을 것 같습니다. 나중에 쿼리를 확인해봐야겠네요.

2023-08-02 13:27 UTC, redcarrot1 commented on backend/src/test/java/org/youcancook/gobong/domain/rating/service/RatingServiceTest.java
스프링 통합 테스트를 작성하신 것 같습니다.
테스트 방법이야 너무 다양하고, 사람마다 조금씩 코드의 차이도 존재하는것 같습니다.

저 같은 경우는 service 레이어는 단위테스트를 진행하고, controller 레이어는 별도의 단위 테스트 없이 통합테스트로 진행하는 것 같습니다.(저도 플젝마다 조금씩 달라지는 것 같아요)

Mock 객체를 사용하는 단위 테스트도 작성해보시면 좋을 것 같습니다.

---

entity 테스트 클래스에서 예외를 테스트하긴 하지만,
현재 클래스가 `@SpringBootTest`인 만큼 평점 등록 실패 또는 수정 실패 케이스도 테스트에 있으면 좋을 것 같습니다.

2023-08-02 13:27 UTC, redcarrot1 commented on backend/src/test/java/org/youcancook/gobong/domain/rating/entity/RatingTest.java
오 entity 테스트는 제가 처음봤습니다.
비즈니스 검증 로직이 entity 내부에 있어서 테스트를 진행하셨군요.👏

2023-08-02 14:04 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/rating/entity/Rating.java
> +    public void validateRatingRange(Integer rating){
서비스단으로 옮겨서 진행합시다 이번에는~!

2023-08-02 15:03 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/rating/entity/Rating.java
> +    public void validateRatingRange(Integer rating){
추가로, 서비스 영역으로 넣기에는 도메인의 역할이 더 큰 것 같아서 이쪽에 넣었어요. 컨트롤러와 직접 만나는 구간에서는 그 일에만 집중하기 위해서였습니다

2023-08-02 15:08 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/rating/service/RatingService.java
> +        recipeRepository.findById(recipeId).orElseThrow(RecipeNotFoundException::new);
[Reference](https://jojoldu.tistory.com/516) 👍🏼

2023-08-02 15:33 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/rating/service/RatingService.java
> +        Rating rating = ratingRepository.findByUserIdAndRecipeId(userId, recipeId)
`userId`나 `recipeId`가 다른 방법으로 변형돼 들어올 경우에 해당 유저가 존재하는지, 또는 해당 레시피가 존재하는지 걸러주기 위함이었습니다. 이에 따라서 예외를 더 정확하게 나타낼 수 있지 않나요?

2023-08-02 15:37 UTC, donghoony commented on backend/src/test/java/org/youcancook/gobong/domain/rating/service/RatingServiceTest.java
서비스단의 단위테스트는 어떤 의미로 제시한 것인가요? 서비스단에서 통합 테스트를 사용하지 않는 이유가 있나요?
저같은 경우는 서비스를 통합테스트로 작성하고, 도메인 단위에서 단위 테스트, 컨트롤러 단위에서는 인수 테스트를 작성하는 방식을 사용해 보았었어요.

2023-08-02 16:06 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/rating/entity/Rating.java
> +    public void validateRatingRange(Integer rating){
위에 올려드린 사이트의 갓영환님의 의견처럼 정답은 없다고 생각합니다!

2023-08-02 16:13 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/rating/entity/Rating.java
> +    public void validateRatingRange(Integer rating){
우리 도메인이 많지 않아서 이걸 이렇게 유지해도 될지, 서비스단으로 넘겨야할지 고민이긴 하네요 🤔

2023-08-02 16:13 UTC, redcarrot1 commented on backend/src/main/java/org/youcancook/gobong/domain/rating/service/RatingService.java
> +        Rating rating = ratingRepository.findByUserIdAndRecipeId(userId, recipeId)
사용자가 평점을 입력했을 때, '잘못된 회원입니다.'와 '잘못된 게시물입니다.'를 분리해서 보여주느냐, 아니면 '잘못된 요청입니다.'로 에러를 감출 것인가를 결정하면 될 것 같습니다.

저는 클라이언트에게 디테일한 에러 정보를 보여주기 위해 DB에 3번의 쿼리를 날릴 필요가 없다고 생각합니다.
혹은 '잘못된 회원'인 경우는 잘 발생하지 않을 것이기에, recipe table에만 쿼리를 날려서 확인하는 방법도 있습니다.

역시 답이 없는 문제이기에 고민해보시고 결정하시면 될 것 같습니다.

결정하시고 코멘트 달아주시면 merge 승인 올리겠습니다!

2023-08-02 16:27 UTC, donghoony commented on backend/src/test/java/org/youcancook/gobong/domain/rating/entity/RatingTest.java
단순한 검증이나 도메인 내부에서 가지고 있는 속성을 한데 모아주는 함수들을 도메인에 작성해서 자연스럽게 작성한 것 같네요 😮

2023-08-02 16:27 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/recipe/entity/Recipe.java
> +    public double getAverageRating(){
이쪽은 공부를 더 해볼게요 🤔

2023-08-02 16:28 UTC, redcarrot1 commented on backend/src/test/java/org/youcancook/gobong/domain/rating/service/RatingServiceTest.java
아래는 저의 **아주 주관적인 생각**입니다.

보통 컨트롤러에서는 인자 확인(bean validation) 정도 수행하고, 나머지 비즈니스 로직은 전부 서비스 레이어에 담게됩니다.
따라서 결국 서비스 레이어의 테스트가 가장 중요하게 됩니다. 따라서 서비스 레이어에서 단위 테스트를 수행합니다. 이때는 스프링의 기술은 최대한 빼고, 자바 코드를 테스트합니다. (`@ExtendWith(MockitoExtension.class)`를 사용합니다.)

통합테스트의 경우 controller, service, repository까지 모든 레이어를 테스트합니다. 실제 스프링 컨테이너를 실행시켜서, 내가 진짜 클라이언트가 된 것처럼 controller에게 api 요청을 보냅니다. (`@SpringBootTest`를 사용합니다. MockMvc를 위해 `@AutoConfigureMockMvc`도 함께 사용합니다.)

아래는 서비스 레이어의 단위 테스트 예시입니다.
```java
@Test
@DisplayName("출석하기 성공 by name")
void saveAttendanceSuccessByName() {
    final String userName = "tester1";
    final Long userId = 1L;
    final String attendancePassword = "1234";

    User user = new User(userName, "password1");
    ReflectionTestUtils.setField(user, "id", userId);

    // given( ) 메서드를 사용해도 좋습니다.
    doReturn(Optional.of(user)).when(userRepository)
            .findByName(userName);
    doReturn(false).when(attendanceRepository)
            .existsByUserAndCreatedAtAfter(eq(user), any(LocalDateTime.class));

    // when
    Long id = attendanceSaveService.saveAttendanceByName(userName, attendancePassword);

    // then
    assertThat(user.getAttendanceNumber()).isEqualTo(1);
    // ...
    // 필요 시 verify 추가
}
```

아래는 통합테스트의 예시입니다.
```java
@Test
@DisplayName("팀의 출석 현황 확인")
void findTeamAttendance() throws Exception {
    // given
    SignupUserDto signupUserDto = new SignupUserDto("tester", "1234");
    userSignupService.addUser(signupUserDto.toEntity());
    String accessToken = userLoginService.loginUser(new LoginUserDto.Request("tester", "1234")).getToken();

    // expected
    // mockMVC를 이용해 request하고, response된 json을 검증합니다.
    mockMvc.perform(get("/api/users/attendances")
                    .contentType(MediaType.APPLICATION_JSON)
                    .header(HttpHeaders.AUTHORIZATION, "Bearer " + accessToken)
            )
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.team").value("복통"))
            .andExpect(jsonPath("$.notAttendance").exists())
            .andExpect(jsonPath("$.attendance").isEmpty())
            .andDo(print());
}
```

2023-08-02 16:29 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/recipe/entity/Recipe.java
> +    public double getAverageRating(){
#6

2023-08-02 16:54 UTC, donghoony commented on backend/src/test/java/org/youcancook/gobong/domain/rating/service/RatingServiceTest.java
작성해주신 통합테스트의 예시가 제가 인수테스트를 작성할 때와 유사한 것 같습니다.. 저는 인수테스트를 `RestAssured`로 해봤었는데 방식이 매우 유사한 것 같아요.

서비스단에서 Mocking을 진행하면 리팩터링을 진행하거나 구현이 조금 바뀔 때마다 테스트를 다시 짜줘야하는 번거로움이 있습니다. 나아가 서비스라는 단어가 말하듯이 비즈니스 전체 흐름 또한 중요하다고 생각했어요. 앞선 코드에서 보셨겠지만 도메인별로 각 단위테스트를 할 수 있는 것들은 이미 빼둔지라, 필요한 비즈니스 로직만 테스트할 수 있도록 진행했습니다.

Mocking을 진행하지 않자는 건 아닙니다.. 외부 라이브러리 (S3 등)를 사용할 때는 의도한 결과를 가지고 테스트하기 위해서 필요한 요소라고 생각해요. 어쩌면 제가 코드를 짜는 방식이 
도메인 구현 -> 서비스 구현 -> 도메인에서만 필요한 필드를 활용하는 함수는 도메인에서 작성 -> 테스트 작성
과 같다 보니, 자연스럽게 생각했던 부분인데 꼼꼼하게 모킹을 통해 하나하나 확인하는 것도 좋은 방법이라는 생각이 들어요

만약 위와 같이 작성한다면, 인수테스트는 따로 작성하지 않나요?

2023-08-02 17:00 UTC, donghoony commented on backend/src/main/java/org/youcancook/gobong/domain/rating/service/RatingService.java
> +        Rating rating = ratingRepository.findByUserIdAndRecipeId(userId, recipeId)
oAuth로 토큰 검증을 통과한 유저가 평점을 남길테니, 확실히 `user`에 대한 검증을 진행할 필요는 없을 것 같습니다. 검증을 통과한 뒤에, 즉시 회원탈퇴를 진행하고 저 리퀘스트를 날릴 수 있을 지는 모르겠네요. 그래도 아마 아래 `rating` 검증에서 걸릴 테니 괜찮아 보입니다.

`recipe`에서는 쿼리를 날리는 편이 나을 듯해요. 클라이언트에게 디테일한 에러 정보를 보여줄 의무는 없지만, 예외가 발생했을 때 로그 등을 통해 어떤 예외가 발생했었는지 알려주면 유지보수하기 좀 더 쉬울 것 같습니다.

사실 이쪽 부분은 코딩할 때에도 `create`와 `update`의 차이가 분명하지 않아서 나누는 게 의미있을까 싶기도 했습니다. `update`가 `create`처럼 기존의 값을 무시하고 덮어쓰기 때문에 그냥 `create`로 해야하나 했지만.. 근본적으로 이 방법이 최선일까도 고민했었는데 결국 다른 방법이 떠오르지 않아 이렇게 진행했어요.

2023-08-03 04:16 UTC, redcarrot1 commented on backend/src/test/java/org/youcancook/gobong/domain/rating/service/RatingServiceTest.java
말씀하신 것처럼 위의 예시코드는 인수 테스트라고 봐야 맞겠네요 🙌

2023-08-03 04:51 UTC, redcarrot1 approved these changes
고생하셨습니다~

2023-08-03 04:52 UTC, merged